name: pdiff
channels:
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.29.1
      - addict==2.4.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - clip==1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.26.0
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - huggingface-hub==0.22.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmengine==0.10.7
      - mmsegmentation==1.2.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==1.26.2
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.1.3
      - pillow==11.2.1
      - platformdirs==4.3.7
      - prettytable==3.16.0
      - psutil==7.0.0
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-msssim==1.0.0
      - pytorch-ssim==0.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.3.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.3
      - termcolor==3.0.1
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - tokenizers==0.13.3
      - tomli==2.2.1
      - torch==2.1.0+cu118
      - torch-fidelity==0.3.0
      - torchvision==0.16.0+cu118
      - tqdm==4.67.1
      - transformers==4.28.0
      - triton==2.1.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - visualizer==0.0.1
      - wcwidth==0.2.13
      - wordcloud==1.9.4
      - yapf==0.43.0
      - zipp==3.21.0
prefix: /home/ys/.conda/envs/pdiff
